language: node_js
node_js:
  - "9"
  - "8"
  - "7"

env:
  - TIMEOUT=15
cache:
  directories:
  - node_modules

before_install:
  - wget -P /tmp https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.11-dea1ce05.tar.gz
  - tar -xvzf /tmp/geth-linux-amd64-1.8.11-dea1ce05.tar.gz -C /tmp
  - chmod a+x /tmp/geth-linux-amd64-1.8.11-dea1ce05/geth

before_script:
  - /tmp/geth-linux-amd64-1.8.11-dea1ce05/geth --dev --nodiscover --maxpeers 0 --ws --wsorigins="*" &
  - sleep 30

script:
  - npm test